# -*- coding: utf-8 -*-
"""Laboratorio7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXiRwP64bIAk_a8QvCqp_82R_J8bTOz4
"""

# Importamos todas las librerias
import pandas as pd
import numpy as np

# Definir los datos de las 8 personas
data = {
    "Nombre": ["Ana", "Carlos", "Beatriz", "David", "Elena", "Francisco", "Gabriela", "Héctor"],
    "Profesión": ["Ingeniera", "Doctor", "Abogada", "Profesor", "Arquitecta", "Escritor", "Chef", "Músico"],
    "País": ["España", "México", "Brasil", "Argentina", "Chile", "Colombia", "Perú", "Ecuador"]
}

# Crear el DataFrame
df_personas = pd.DataFrame(data)

# Imprimir el DataFrame
print(df_personas)

#Leyendo un archivo de tipo csv
df = pd.read_csv('data.csv')
print(df)

# muestra los 5 primeros registros del dataframe
df.head()

# Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar
# un resumen estadístico de los datos.
import pandas as pd
df_random = pd.DataFrame(np.random.rand(100,8))
df_random.head(10)

# Resumen estadistico de los datos
df_random.describe()

"""Parte 2"""

# Crear un array de números del 1 al 10
# mostrar la suma, la media, y el valor máximo.

array=np.arange(1,11)
print(array)
suma = np.sum(array)
print("Suma:", suma)
media = np.mean(array)
print("Media:", media)
maximo = np.max(array)
print("Máximo:", maximo)

# Crear un array de 3x4 lleno de ceros
#y luego cambiar su forma a 2x6
array_ceros = np.zeros((3, 4))
print("Array original:\n", array_ceros)
array_modificado = array_ceros.reshape(2, 6)
print("\nArray modificado:\n", array_modificado)

matriz_aleatoria = np.random.rand(3, 3)
print("Matriz aleatoria:\n", matriz_aleatoria)
matriz_transpuesta = matriz_aleatoria.T
print("\nMatriz transpuesta:\n", matriz_transpuesta)

# concatenar dos arrays
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([6, 7, 8, 9, 10])
array_concatenado = np.concatenate((array_1, array_2))
print (array_concatenado)